# Generated by Django 3.2.15 on 2023-01-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('GSTnumber', models.CharField(max_length=20, null=True)),
                ('AadharNumber', models.CharField(max_length=15, null=True)),
                ('CreditScore', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
