# Generated by Django 3.2.15 on 2023-01-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='WalletAddress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
