# Generated by Django 3.2.15 on 2023-01-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_gstnumber_kyc_pannumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='WalletAddress',
        ),
    ]
