# Generated by Django 3.2.15 on 2023-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_kyc_creditscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='CreditScore',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
