# Generated by Django 3.2.15 on 2023-01-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_kyc_creditscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='WalletAddress',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kyc',
            name='CreditScore',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
