# Generated by Django 3.2.15 on 2023-01-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_kyc_walletaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='WalletAddress',
        ),
    ]
