# Generated by Django 3.2.15 on 2023-01-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_kyc_walletaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='WalletAddress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
