# Generated by Django 3.2.15 on 2023-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_kyc_walletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='WalletAddress',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
